/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.tccz.tccz.common.dal.daointerface;

// auto generated imports
import com.tccz.tccz.common.dal.dataobject.DiscountChangeDO;
import java.util.List;
import org.springframework.dao.DataAccessException;

/**
 * A dao interface provides methods to access database table <tt>discount_change</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/discount_change.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public interface DiscountChangeDAO {
	/**
	 *  Query DB table <tt>discount_change</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from discount_change where (discount_id = ?)</tt>
	 *
	 *	@param discountId
	 *	@return List<DiscountChangeDO>
	 *	@throws DataAccessException
	 */	 
    public List<DiscountChangeDO> getByDiscountId(int discountId) throws DataAccessException;

	/**
	 *  Insert one <tt>DiscountChangeDO</tt> object to DB table <tt>discount_change</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into discount_change(discount_id,state,create_time) values (?, ?, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param discountChange
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(DiscountChangeDO discountChange) throws DataAccessException;

}