/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.tccz.tccz.common.dal.daointerface;

// auto generated imports
import com.tccz.tccz.common.dal.dataobject.EnterpriseDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import com.tccz.tccz.dal.util.PageList;

/**
 * A dao interface provides methods to access database table <tt>enterprise</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/enterprise.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public interface EnterpriseDAO {
	/**
	 *  Query DB table <tt>enterprise</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from enterprise where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return EnterpriseDO
	 *	@throws DataAccessException
	 */	 
    public EnterpriseDO getById(int id) throws DataAccessException;

	/**
	 *  Query DB table <tt>enterprise</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from enterprise where (institution_code = ?)</tt>
	 *
	 *	@param institutionCode
	 *	@return EnterpriseDO
	 *	@throws DataAccessException
	 */	 
    public EnterpriseDO getEnterpriseByCode(String institutionCode) throws DataAccessException;

	/**
	 *  Query DB table <tt>enterprise</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select e.* from enterprise</tt>
	 *
	 *	@param legalPersonIdCard
	 *	@return List<EnterpriseDO>
	 *	@throws DataAccessException
	 */	 
    public List<EnterpriseDO> getByLegalPersonIdCard(String legalPersonIdCard) throws DataAccessException;

	/**
	 *  Query DB table <tt>enterprise</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from enterprise</tt>
	 *
	 *	@param enterpriseName
	 *	@return List<EnterpriseDO>
	 *	@throws DataAccessException
	 */	 
    public List<EnterpriseDO> fuzzyQueryByName(String enterpriseName) throws DataAccessException;

	/**
	 *  Query DB table <tt>enterprise</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from enterprise</tt>
	 *
	 *	@param enterpriseName
	 *	@param pageSize
	 *	@param pageNum
	 *	@return PageList
	 *	@throws DataAccessException
	 */	 
    public PageList fuzzyPageQueryByName(String enterpriseName, int pageSize, int pageNum) throws DataAccessException;

	/**
	 *  Insert one <tt>EnterpriseDO</tt> object to DB table <tt>enterprise</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into enterprise(name,institution_code,account_number,create_time,modify_time) values (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param enterprise
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(EnterpriseDO enterprise) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>enterprise</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from enterprise where (institution_code = ?)</tt>
	 *
	 *	@param institutionCode
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int delete(String institutionCode) throws DataAccessException;

	/**
	 *  Update DB table <tt>enterprise</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update enterprise set name=?, account_number=?, modify_time=CURRENT_TIMESTAMP where (institution_code = ?)</tt>
	 *
	 *	@param enterprise
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(EnterpriseDO enterprise) throws DataAccessException;

}