/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.tccz.tccz.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tccz.tccz.common.dal.daointerface.PersonDAO;

// auto generated imports
import com.tccz.tccz.common.dal.dataobject.PersonDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import com.tccz.tccz.dal.util.PageList;
import com.tccz.tccz.common.dal.dataobject.PersonDO;
import java.util.Map;
import java.util.HashMap;
import com.tccz.tccz.dal.util.Paginator;

import java.util.HashMap;
import java.util.Map;

/**
 * An ibatis based implementation of dao interface <tt>com.tccz.tccz.common.dal.daointerface.PersonDAO</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/person.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class IbatisPersonDAO extends SqlMapClientDaoSupport implements PersonDAO {
	/**
	 *  Insert one <tt>PersonDO</tt> object to DB table <tt>person</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into person(name,id_card_number,account_number,create_time,modify_time) values (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param person
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(PersonDO person) throws DataAccessException {
    	if (person == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-PERSON-INSERT", person);

        return person.getId();
    }

	/**
	 *  Update DB table <tt>person</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update person set name=?, account_number=?, modify_time=CURRENT_TIMESTAMP where (id_card_number = ?)</tt>
	 *
	 *	@param person
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(PersonDO person) throws DataAccessException {
    	if (person == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-PERSON-UPDATE", person);
    }

	/**
	 *  Delete records from DB table <tt>person</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from person where (id_card_number = ?)</tt>
	 *
	 *	@param idCardNumber
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int delete(String idCardNumber) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-PERSON-DELETE", idCardNumber);
    }

	/**
	 *  Query DB table <tt>person</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from person where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return PersonDO
	 *	@throws DataAccessException
	 */	 
    public PersonDO getById(int id) throws DataAccessException {
        Integer param = new Integer(id);
        return (PersonDO) getSqlMapClientTemplate().queryForObject("MS-PERSON-GET-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>person</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from person where (id_card_number = ?)</tt>
	 *
	 *	@param idCardNumber
	 *	@return PersonDO
	 *	@throws DataAccessException
	 */	 
    public PersonDO getByIdCard(String idCardNumber) throws DataAccessException {

        return (PersonDO) getSqlMapClientTemplate().queryForObject("MS-PERSON-GET-BY-ID-CARD", idCardNumber);

    }

	/**
	 *  Query DB table <tt>person</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from person</tt>
	 *
	 *	@param fuzzyName
	 *	@return List<PersonDO>
	 *	@throws DataAccessException
	 */	 
    public List<PersonDO> fuzzyQueryByName(String fuzzyName) throws DataAccessException {
	    Map param = new HashMap();

					        param.put("fuzzyName", fuzzyName);
					        return getSqlMapClientTemplate().queryForList("MS-PERSON-FUZZY-QUERY-BY-NAME", param);

    }

	/**
	 *  Query DB table <tt>person</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from person</tt>
	 *
	 *	@param personName
	 *	@param pageSize
	 *	@param pageNum
	 *	@return PageList
	 *	@throws DataAccessException
	 */	 
    public PageList fuzzyPageQueryByName(String personName, int pageSize, int pageNum) throws DataAccessException {
        Map param = new HashMap();

        param.put("personName", personName);
        param.put("pageSize", new Integer(pageSize));
        param.put("pageNum", new Integer(pageNum));

        Paginator paginator = new Paginator();
        paginator.setItemsPerPage(pageSize);
        paginator.setPage(pageNum / pageSize + 1);

        paginator.setItems(((Integer) getSqlMapClientTemplate().queryForObject("MS-TCCZ-PERSON-FUZZY-PAGE-QUERY-BY-NAME-COUNT-FOR-PAGING", param)).intValue());
        
        PageList  pageList = new PageList();
        pageList.setPaginator(paginator);
        
        if (paginator.getBeginIndex() <= paginator.getItems()) {
            param.put("startRow", new Integer(paginator.getBeginIndex()));
            param.put("endRow", new Integer(paginator.getEndIndex()));
            pageList.addAll(getSqlMapClientTemplate().queryForList("MS-PERSON-FUZZY-PAGE-QUERY-BY-NAME", param));
        }
        
        return pageList;
    }

}