/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.tccz.tccz.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tccz.tccz.common.dal.daointerface.DiscountChangeDAO;

// auto generated imports
import com.tccz.tccz.common.dal.dataobject.DiscountChangeDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import com.tccz.tccz.common.dal.dataobject.DiscountChangeDO;

/**
 * An ibatis based implementation of dao interface <tt>com.tccz.tccz.common.dal.daointerface.DiscountChangeDAO</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/discount_change.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class IbatisDiscountChangeDAO extends SqlMapClientDaoSupport implements DiscountChangeDAO {
	/**
	 *  Query DB table <tt>discount_change</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from discount_change where (discount_id = ?) order by create_time DESC</tt>
	 *
	 *	@param discountId
	 *	@return List<DiscountChangeDO>
	 *	@throws DataAccessException
	 */	 
    public List<DiscountChangeDO> getByDiscountId(int discountId) throws DataAccessException {
        Integer param = new Integer(discountId);
        return getSqlMapClientTemplate().queryForList("MS-DISCOUNT-CHANGE-GET-BY-DISCOUNT-ID", param);

    }

	/**
	 *  Insert one <tt>DiscountChangeDO</tt> object to DB table <tt>discount_change</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into discount_change(discount_id,state,create_time) values (?, ?, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param discountChange
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(DiscountChangeDO discountChange) throws DataAccessException {
    	if (discountChange == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-DISCOUNT-CHANGE-INSERT", discountChange);

        return discountChange.getId();
    }

}