/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.tccz.tccz.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tccz.tccz.common.dal.daointerface.EnterpriseDAO;

// auto generated imports
import com.tccz.tccz.common.dal.dataobject.EnterpriseDO;
import org.springframework.dao.DataAccessException;

/**
 * An ibatis based implementation of dao interface <tt>com.tccz.tccz.common.dal.daointerface.EnterpriseDAO</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/enterprise.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class IbatisEnterpriseDAO extends SqlMapClientDaoSupport implements EnterpriseDAO {
	/**
	 *  Query DB table <tt>enterprise</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from enterprise where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return EnterpriseDO
	 *	@throws DataAccessException
	 */	 
    public EnterpriseDO getById(int id) throws DataAccessException {
        Integer param = new Integer(id);
        return (EnterpriseDO) getSqlMapClientTemplate().queryForObject("MS-ENTERPRISE-GET-BY-ID", param);

    }

}