/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.tccz.tccz.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tccz.tccz.common.dal.daointerface.DiscountDAO;

// auto generated imports
import com.tccz.tccz.common.dal.dataobject.DiscountDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import com.tccz.tccz.common.dal.dataobject.DiscountDO;

/**
 * An ibatis based implementation of dao interface <tt>com.tccz.tccz.common.dal.daointerface.DiscountDAO</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/discount.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class IbatisDiscountDAO extends SqlMapClientDaoSupport implements DiscountDAO {
	/**
	 *  Query DB table <tt>discount</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from discount where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return DiscountDO
	 *	@throws DataAccessException
	 */	 
    public DiscountDO getById(int id) throws DataAccessException {
        Integer param = new Integer(id);
        return (DiscountDO) getSqlMapClientTemplate().queryForObject("MS-DISCOUNT-GET-BY-ID", param);

    }

	/**
	 *  Query DB table <tt>discount</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from discount</tt>
	 *
	 *	@return List<DiscountDO>
	 *	@throws DataAccessException
	 */	 
    public List<DiscountDO> getAll() throws DataAccessException {

        return getSqlMapClientTemplate().queryForList("MS-DISCOUNT-GET-ALL", null);

    }

}